In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("Social_Network_Ads.csv")
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
df = df.drop("User ID", axis=1)
df

     Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [6]:
df.isnull().sum()

Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [7]:
df = pd.get_dummies(df, dtype=int, drop_first=True)
df

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [8]:
X = df.drop("Purchased", axis=1)
X

     Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [9]:
y = df["Purchased"]
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [10]:
df["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Gaussian Naive Bayes

In [14]:
from sklearn.naive_bayes import GaussianNB
gaussian_model = GaussianNB()
gaussian_model.fit(X_train, y_train)

# Model Prediction
y_pred = gaussian_model.predict(X_test)

# Model Evaluation
from sklearn.metrics import confusion_matrix, classification_report
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

clf_report = classification_report(y_test, y_pred)
print(clf_report)

[[50  2]
 [ 3 25]]
              precision    recall  f1-score   support

           0       0.94      0.96      0.95        52
           1       0.93      0.89      0.91        28

    accuracy                           0.94        80
   macro avg       0.93      0.93      0.93        80
weighted avg       0.94      0.94      0.94        80

# MultinomialNB

In [15]:
from sklearn.naive_bayes import MultinomialNB
multinomial_model = MultinomialNB()
multinomial_model.fit(X_train, y_train)

# Model Prediction
y_pred = multinomial_model.predict(X_test)

# Model Evaluation
from sklearn.metrics import confusion_matrix, classification_report
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

clf_report = classification_report(y_test, y_pred)
print(clf_report)

[[38 14]
 [18 10]]
              precision    recall  f1-score   support

           0       0.68      0.73      0.70        52
           1       0.42      0.36      0.38        28

    accuracy                           0.60        80
   macro avg       0.55      0.54      0.54        80
weighted avg       0.59      0.60      0.59        80

# ComplementNB

In [16]:

from sklearn.naive_bayes import ComplementNB
complement_model = ComplementNB()
complement_model.fit(X_train, y_train)

# Model Prediction
y_pred = complement_model.predict(X_test)

# Model Evaluation
from sklearn.metrics import confusion_matrix, classification_report
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

clf_report = classification_report(y_test, y_pred)
print(clf_report)

[[27 25]
 [15 13]]
              precision    recall  f1-score   support

           0       0.64      0.52      0.57        52
           1       0.34      0.46      0.39        28

    accuracy                           0.50        80
   macro avg       0.49      0.49      0.48        80
weighted avg       0.54      0.50      0.51        80

# BernoulliNB

In [17]:

from sklearn.naive_bayes import BernoulliNB
bernoulli_model = BernoulliNB()
bernoulli_model.fit(X_train, y_train)

# Model Prediction
y_pred = bernoulli_model.predict(X_test)

# Model Evaluation
from sklearn.metrics import confusion_matrix, classification_report
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

clf_report = classification_report(y_test, y_pred)
print(clf_report)

[[52  0]
 [28  0]]
              precision    recall  f1-score   support

           0       0.65      1.00      0.79        52
           1       0.00      0.00      0.00        28

    accuracy                           0.65        80
   macro avg       0.33      0.50      0.39        80
weighted avg       0.42      0.65      0.51        80

C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# CategoricalNB

In [18]:

from sklearn.naive_bayes import CategoricalNB
categorical_model = CategoricalNB()
categorical_model.fit(X_train, y_train)

# Model Prediction
y_pred = categorical_model.predict(X_test)

# Model Evaluation
from sklearn.metrics import confusion_matrix, classification_report
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

clf_report = classification_report(y_test, y_pred)
print(clf_report)

[[50  2]
 [12 16]]
              precision    recall  f1-score   support

           0       0.81      0.96      0.88        52
           1       0.89      0.57      0.70        28

    accuracy                           0.82        80
   macro avg       0.85      0.77      0.79        80
weighted avg       0.84      0.82      0.81        80