In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Social_Network_Ads.csv")
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
df = df.drop("User ID", axis=1)
df

     Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [4]:
df.isnull().sum()

Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [5]:
df = pd.get_dummies(df, dtype=int, drop_first=True)
df

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [6]:
X = df.drop("Purchased", axis=1)
X

     Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [7]:
y = df["Purchased"]
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [8]:
df["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# AdaBoostClassifier

In [11]:
from sklearn.ensemble import AdaBoostClassifier
ada_model = AdaBoostClassifier(n_estimators=100, random_state=0)
ada_model.fit(X_train, y_train)

# Model Prediction
y_pred = ada_model.predict(X_test)

# Model Evaluation
from sklearn.metrics import confusion_matrix, classification_report
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

clf_report = classification_report(y_test, y_pred)
print(clf_report)

[[49  3]
 [ 5 23]]
              precision    recall  f1-score   support

           0       0.91      0.94      0.92        52
           1       0.88      0.82      0.85        28

    accuracy                           0.90        80
   macro avg       0.90      0.88      0.89        80
weighted avg       0.90      0.90      0.90        80

# GradientBoostingClassifier

In [12]:
from sklearn.ensemble import GradientBoostingClassifier
gradient_model = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,
    max_depth=1, random_state=0)
gradient_model.fit(X_train, y_train)

# Model Prediction
y_pred = gradient_model.predict(X_test)

# Model Evaluation
from sklearn.metrics import confusion_matrix, classification_report
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

clf_report = classification_report(y_test, y_pred)
print(clf_report)

[[48  4]
 [ 7 21]]
              precision    recall  f1-score   support

           0       0.87      0.92      0.90        52
           1       0.84      0.75      0.79        28

    accuracy                           0.86        80
   macro avg       0.86      0.84      0.84        80
weighted avg       0.86      0.86      0.86        80

# HistGradientBoostingClassifier

In [13]:
from sklearn.ensemble import HistGradientBoostingClassifier
hist_gradient_model = HistGradientBoostingClassifier()
hist_gradient_model.fit(X_train, y_train)

# Model Prediction
y_pred = hist_gradient_model.predict(X_test)

# Model Evaluation
from sklearn.metrics import confusion_matrix, classification_report
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

clf_report = classification_report(y_test, y_pred)
print(clf_report)

[[47  5]
 [ 4 24]]
              precision    recall  f1-score   support

           0       0.92      0.90      0.91        52
           1       0.83      0.86      0.84        28

    accuracy                           0.89        80
   macro avg       0.87      0.88      0.88        80
weighted avg       0.89      0.89      0.89        80